//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 01:40:41 PM EDT 
//


package com.phdcc.homehealth;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the homehealth.json package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: homehealth.json
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HL7Message }
     * 
     */
    public HL7Message createHL7Message() {
        return new HL7Message();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 }
     * 
     */
    public HL7Message.IN2 createHL7MessageIN2() {
        return new HL7Message.IN2();
    }

    /**
     * Create an instance of {@link HL7Message.IN1 }
     * 
     */
    public HL7Message.IN1 createHL7MessageIN1() {
        return new HL7Message.IN1();
    }

    /**
     * Create an instance of {@link HL7Message.GT1 }
     * 
     */
    public HL7Message.GT1 createHL7MessageGT1() {
        return new HL7Message.GT1();
    }

    /**
     * Create an instance of {@link HL7Message.ROL }
     * 
     */
    public HL7Message.ROL createHL7MessageROL() {
        return new HL7Message.ROL();
    }

    /**
     * Create an instance of {@link HL7Message.PR1 }
     * 
     */
    public HL7Message.PR1 createHL7MessagePR1() {
        return new HL7Message.PR1();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 }
     * 
     */
    public HL7Message.DG1 createHL7MessageDG1() {
        return new HL7Message.DG1();
    }

    /**
     * Create an instance of {@link HL7Message.AL1 }
     * 
     */
    public HL7Message.AL1 createHL7MessageAL1() {
        return new HL7Message.AL1();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 }
     * 
     */
    public HL7Message.PV1 createHL7MessagePV1() {
        return new HL7Message.PV1();
    }

    /**
     * Create an instance of {@link HL7Message.NK1 }
     * 
     */
    public HL7Message.NK1 createHL7MessageNK1() {
        return new HL7Message.NK1();
    }

    /**
     * Create an instance of {@link HL7Message.PID }
     * 
     */
    public HL7Message.PID createHL7MessagePID() {
        return new HL7Message.PID();
    }

    /**
     * Create an instance of {@link HL7Message.EVN }
     * 
     */
    public HL7Message.EVN createHL7MessageEVN() {
        return new HL7Message.EVN();
    }

    /**
     * Create an instance of {@link HL7Message.MSH }
     * 
     */
    public HL7Message.MSH createHL7MessageMSH() {
        return new HL7Message.MSH();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .IN21 }
     * 
     */
    public HL7Message.IN2 .IN21 createHL7MessageIN2IN21() {
        return new HL7Message.IN2 .IN21();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .IN22 }
     * 
     */
    public HL7Message.IN2 .IN22 createHL7MessageIN2IN22() {
        return new HL7Message.IN2 .IN22();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .ROL1 }
     * 
     */
    public HL7Message.IN2 .ROL1 createHL7MessageIN2ROL1() {
        return new HL7Message.IN2 .ROL1();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .ROL2 }
     * 
     */
    public HL7Message.IN2 .ROL2 createHL7MessageIN2ROL2() {
        return new HL7Message.IN2 .ROL2();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .ROL3 }
     * 
     */
    public HL7Message.IN2 .ROL3 createHL7MessageIN2ROL3() {
        return new HL7Message.IN2 .ROL3();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .ROL4 }
     * 
     */
    public HL7Message.IN2 .ROL4 createHL7MessageIN2ROL4() {
        return new HL7Message.IN2 .ROL4();
    }

    /**
     * Create an instance of {@link HL7Message.IN2 .ROL5 }
     * 
     */
    public HL7Message.IN2 .ROL5 createHL7MessageIN2ROL5() {
        return new HL7Message.IN2 .ROL5();
    }

    /**
     * Create an instance of {@link HL7Message.IN1 .IN11 }
     * 
     */
    public HL7Message.IN1 .IN11 createHL7MessageIN1IN11() {
        return new HL7Message.IN1 .IN11();
    }

    /**
     * Create an instance of {@link HL7Message.IN1 .IN12 }
     * 
     */
    public HL7Message.IN1 .IN12 createHL7MessageIN1IN12() {
        return new HL7Message.IN1 .IN12();
    }

    /**
     * Create an instance of {@link HL7Message.IN1 .IN13 }
     * 
     */
    public HL7Message.IN1 .IN13 createHL7MessageIN1IN13() {
        return new HL7Message.IN1 .IN13();
    }

    /**
     * Create an instance of {@link HL7Message.IN1 .IN14 }
     * 
     */
    public HL7Message.IN1 .IN14 createHL7MessageIN1IN14() {
        return new HL7Message.IN1 .IN14();
    }

    /**
     * Create an instance of {@link HL7Message.IN1 .IN19 }
     * 
     */
    public HL7Message.IN1 .IN19 createHL7MessageIN1IN19() {
        return new HL7Message.IN1 .IN19();
    }

    /**
     * Create an instance of {@link HL7Message.GT1 .GT11 }
     * 
     */
    public HL7Message.GT1 .GT11 createHL7MessageGT1GT11() {
        return new HL7Message.GT1 .GT11();
    }

    /**
     * Create an instance of {@link HL7Message.GT1 .GT12 }
     * 
     */
    public HL7Message.GT1 .GT12 createHL7MessageGT1GT12() {
        return new HL7Message.GT1 .GT12();
    }

    /**
     * Create an instance of {@link HL7Message.GT1 .GT13 }
     * 
     */
    public HL7Message.GT1 .GT13 createHL7MessageGT1GT13() {
        return new HL7Message.GT1 .GT13();
    }

    /**
     * Create an instance of {@link HL7Message.ROL.ROL1 }
     * 
     */
    public HL7Message.ROL.ROL1 createHL7MessageROLROL1() {
        return new HL7Message.ROL.ROL1();
    }

    /**
     * Create an instance of {@link HL7Message.ROL.ROL2 }
     * 
     */
    public HL7Message.ROL.ROL2 createHL7MessageROLROL2() {
        return new HL7Message.ROL.ROL2();
    }

    /**
     * Create an instance of {@link HL7Message.ROL.ROL3 }
     * 
     */
    public HL7Message.ROL.ROL3 createHL7MessageROLROL3() {
        return new HL7Message.ROL.ROL3();
    }

    /**
     * Create an instance of {@link HL7Message.ROL.ROL4 }
     * 
     */
    public HL7Message.ROL.ROL4 createHL7MessageROLROL4() {
        return new HL7Message.ROL.ROL4();
    }

    /**
     * Create an instance of {@link HL7Message.ROL.ROL5 }
     * 
     */
    public HL7Message.ROL.ROL5 createHL7MessageROLROL5() {
        return new HL7Message.ROL.ROL5();
    }

    /**
     * Create an instance of {@link HL7Message.PR1 .PR11 }
     * 
     */
    public HL7Message.PR1 .PR11 createHL7MessagePR1PR11() {
        return new HL7Message.PR1 .PR11();
    }

    /**
     * Create an instance of {@link HL7Message.PR1 .PR12 }
     * 
     */
    public HL7Message.PR1 .PR12 createHL7MessagePR1PR12() {
        return new HL7Message.PR1 .PR12();
    }

    /**
     * Create an instance of {@link HL7Message.PR1 .PR13 }
     * 
     */
    public HL7Message.PR1 .PR13 createHL7MessagePR1PR13() {
        return new HL7Message.PR1 .PR13();
    }

    /**
     * Create an instance of {@link HL7Message.PR1 .PR14 }
     * 
     */
    public HL7Message.PR1 .PR14 createHL7MessagePR1PR14() {
        return new HL7Message.PR1 .PR14();
    }

    /**
     * Create an instance of {@link HL7Message.PR1 .PR15 }
     * 
     */
    public HL7Message.PR1 .PR15 createHL7MessagePR1PR15() {
        return new HL7Message.PR1 .PR15();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 .DG11 }
     * 
     */
    public HL7Message.DG1 .DG11 createHL7MessageDG1DG11() {
        return new HL7Message.DG1 .DG11();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 .DG12 }
     * 
     */
    public HL7Message.DG1 .DG12 createHL7MessageDG1DG12() {
        return new HL7Message.DG1 .DG12();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 .DG13 }
     * 
     */
    public HL7Message.DG1 .DG13 createHL7MessageDG1DG13() {
        return new HL7Message.DG1 .DG13();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 .DG14 }
     * 
     */
    public HL7Message.DG1 .DG14 createHL7MessageDG1DG14() {
        return new HL7Message.DG1 .DG14();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 .DG15 }
     * 
     */
    public HL7Message.DG1 .DG15 createHL7MessageDG1DG15() {
        return new HL7Message.DG1 .DG15();
    }

    /**
     * Create an instance of {@link HL7Message.DG1 .DG16 }
     * 
     */
    public HL7Message.DG1 .DG16 createHL7MessageDG1DG16() {
        return new HL7Message.DG1 .DG16();
    }

    /**
     * Create an instance of {@link HL7Message.AL1 .AL11 }
     * 
     */
    public HL7Message.AL1 .AL11 createHL7MessageAL1AL11() {
        return new HL7Message.AL1 .AL11();
    }

    /**
     * Create an instance of {@link HL7Message.AL1 .AL13 }
     * 
     */
    public HL7Message.AL1 .AL13 createHL7MessageAL1AL13() {
        return new HL7Message.AL1 .AL13();
    }

    /**
     * Create an instance of {@link HL7Message.AL1 .AL15 }
     * 
     */
    public HL7Message.AL1 .AL15 createHL7MessageAL1AL15() {
        return new HL7Message.AL1 .AL15();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV11 }
     * 
     */
    public HL7Message.PV1 .PV11 createHL7MessagePV1PV11() {
        return new HL7Message.PV1 .PV11();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV12 }
     * 
     */
    public HL7Message.PV1 .PV12 createHL7MessagePV1PV12() {
        return new HL7Message.PV1 .PV12();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV13 }
     * 
     */
    public HL7Message.PV1 .PV13 createHL7MessagePV1PV13() {
        return new HL7Message.PV1 .PV13();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV17 }
     * 
     */
    public HL7Message.PV1 .PV17 createHL7MessagePV1PV17() {
        return new HL7Message.PV1 .PV17();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV110 }
     * 
     */
    public HL7Message.PV1 .PV110 createHL7MessagePV1PV110() {
        return new HL7Message.PV1 .PV110();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV112 }
     * 
     */
    public HL7Message.PV1 .PV112 createHL7MessagePV1PV112() {
        return new HL7Message.PV1 .PV112();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV114 }
     * 
     */
    public HL7Message.PV1 .PV114 createHL7MessagePV1PV114() {
        return new HL7Message.PV1 .PV114();
    }

    /**
     * Create an instance of {@link HL7Message.PV1 .PV115 }
     * 
     */
    public HL7Message.PV1 .PV115 createHL7MessagePV1PV115() {
        return new HL7Message.PV1 .PV115();
    }

    /**
     * Create an instance of {@link HL7Message.NK1 .NK11 }
     * 
     */
    public HL7Message.NK1 .NK11 createHL7MessageNK1NK11() {
        return new HL7Message.NK1 .NK11();
    }

    /**
     * Create an instance of {@link HL7Message.NK1 .NK12 }
     * 
     */
    public HL7Message.NK1 .NK12 createHL7MessageNK1NK12() {
        return new HL7Message.NK1 .NK12();
    }

    /**
     * Create an instance of {@link HL7Message.NK1 .NK13 }
     * 
     */
    public HL7Message.NK1 .NK13 createHL7MessageNK1NK13() {
        return new HL7Message.NK1 .NK13();
    }

    /**
     * Create an instance of {@link HL7Message.NK1 .NK18 }
     * 
     */
    public HL7Message.NK1 .NK18 createHL7MessageNK1NK18() {
        return new HL7Message.NK1 .NK18();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID3 }
     * 
     */
    public HL7Message.PID.PID3 createHL7MessagePIDPID3() {
        return new HL7Message.PID.PID3();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID5 }
     * 
     */
    public HL7Message.PID.PID5 createHL7MessagePIDPID5() {
        return new HL7Message.PID.PID5();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID7 }
     * 
     */
    public HL7Message.PID.PID7 createHL7MessagePIDPID7() {
        return new HL7Message.PID.PID7();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID8 }
     * 
     */
    public HL7Message.PID.PID8 createHL7MessagePIDPID8() {
        return new HL7Message.PID.PID8();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID10 }
     * 
     */
    public HL7Message.PID.PID10 createHL7MessagePIDPID10() {
        return new HL7Message.PID.PID10();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID11 }
     * 
     */
    public HL7Message.PID.PID11 createHL7MessagePIDPID11() {
        return new HL7Message.PID.PID11();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID12 }
     * 
     */
    public HL7Message.PID.PID12 createHL7MessagePIDPID12() {
        return new HL7Message.PID.PID12();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID13 }
     * 
     */
    public HL7Message.PID.PID13 createHL7MessagePIDPID13() {
        return new HL7Message.PID.PID13();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID14 }
     * 
     */
    public HL7Message.PID.PID14 createHL7MessagePIDPID14() {
        return new HL7Message.PID.PID14();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID16 }
     * 
     */
    public HL7Message.PID.PID16 createHL7MessagePIDPID16() {
        return new HL7Message.PID.PID16();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID18 }
     * 
     */
    public HL7Message.PID.PID18 createHL7MessagePIDPID18() {
        return new HL7Message.PID.PID18();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID19 }
     * 
     */
    public HL7Message.PID.PID19 createHL7MessagePIDPID19() {
        return new HL7Message.PID.PID19();
    }

    /**
     * Create an instance of {@link HL7Message.PID.PID20 }
     * 
     */
    public HL7Message.PID.PID20 createHL7MessagePIDPID20() {
        return new HL7Message.PID.PID20();
    }

    /**
     * Create an instance of {@link HL7Message.EVN.EVN1 }
     * 
     */
    public HL7Message.EVN.EVN1 createHL7MessageEVNEVN1() {
        return new HL7Message.EVN.EVN1();
    }

    /**
     * Create an instance of {@link HL7Message.EVN.EVN2 }
     * 
     */
    public HL7Message.EVN.EVN2 createHL7MessageEVNEVN2() {
        return new HL7Message.EVN.EVN2();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH3 }
     * 
     */
    public HL7Message.MSH.MSH3 createHL7MessageMSHMSH3() {
        return new HL7Message.MSH.MSH3();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH4 }
     * 
     */
    public HL7Message.MSH.MSH4 createHL7MessageMSHMSH4() {
        return new HL7Message.MSH.MSH4();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH5 }
     * 
     */
    public HL7Message.MSH.MSH5 createHL7MessageMSHMSH5() {
        return new HL7Message.MSH.MSH5();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH6 }
     * 
     */
    public HL7Message.MSH.MSH6 createHL7MessageMSHMSH6() {
        return new HL7Message.MSH.MSH6();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH7 }
     * 
     */
    public HL7Message.MSH.MSH7 createHL7MessageMSHMSH7() {
        return new HL7Message.MSH.MSH7();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH8 }
     * 
     */
    public HL7Message.MSH.MSH8 createHL7MessageMSHMSH8() {
        return new HL7Message.MSH.MSH8();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH9 }
     * 
     */
    public HL7Message.MSH.MSH9 createHL7MessageMSHMSH9() {
        return new HL7Message.MSH.MSH9();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH10 }
     * 
     */
    public HL7Message.MSH.MSH10 createHL7MessageMSHMSH10() {
        return new HL7Message.MSH.MSH10();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH11 }
     * 
     */
    public HL7Message.MSH.MSH11 createHL7MessageMSHMSH11() {
        return new HL7Message.MSH.MSH11();
    }

    /**
     * Create an instance of {@link HL7Message.MSH.MSH12 }
     * 
     */
    public HL7Message.MSH.MSH12 createHL7MessageMSHMSH12() {
        return new HL7Message.MSH.MSH12();
    }

}
